# Generated by Django 5.1.3 on 2024-11-30 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('em andamento', 'em andamento'), ('concluido', 'concluido')], default='pendente', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
